# Default config
# Provides defaults for all gem invocations.
# All values may be overridden by the config in the method invocation.
#
# Snapshot retention settings
# There is no capability to snapshot a volume more than once per day.
retain_for_days: 14 # keep every day for <retain_for_days> days
interval_days: 7 # every <interval_days> keep one snapshot for <interval_days * intervals> days
intervals: 4

# Log file location
log_file_path: log.log
log_level: info

# A short description to identify the snapshot
# This tool creates the snapshot with description as "<namespace>-<Time>".
# e.g ebs-snapshot-2014-11-10.110630
namespace: EbsSnapshots

exclude_devices:
  - /dev/sda1 # typically this is the root volume on paravirtual and hvm
instance_names: []
instance_ids: []
image_ids: []
